name: redcross_monaragala
description: "Redcross Monaragala"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  flutter_riverpod: ^2.6.1
  auto_route: ^9.2.2
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
